stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building"
    - mdir build
    - touch build/info.text

test:
  stage: test
  script:
    - echo "Testing"
    - test -f "build/info.txt